# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\palmtale@live.com\Weiyun\Workspace\eric\palmcoin\ui/main.ui'
#
# Created: Tue Jan  7 01:17:27 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(553, 621)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.platformLab = QtGui.QLabel(self.centralWidget)
        self.platformLab.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.platformLab.setObjectName(_fromUtf8("platformLab"))
        self.platformInfo = QtGui.QLabel(self.centralWidget)
        self.platformInfo.setGeometry(QtCore.QRect(80, 20, 81, 16))
        self.platformInfo.setStyleSheet(_fromUtf8("color: rgb(0, 85, 255);"))
        self.platformInfo.setText(_fromUtf8(""))
        self.platformInfo.setObjectName(_fromUtf8("platformInfo"))
        self.userNameLab = QtGui.QLabel(self.centralWidget)
        self.userNameLab.setGeometry(QtCore.QRect(170, 20, 61, 16))
        self.userNameLab.setStyleSheet(_fromUtf8(""))
        self.userNameLab.setObjectName(_fromUtf8("userNameLab"))
        self.userNameInfo = QtGui.QLabel(self.centralWidget)
        self.userNameInfo.setGeometry(QtCore.QRect(250, 20, 261, 16))
        self.userNameInfo.setStyleSheet(_fromUtf8("color: rgb(255, 170, 0);"))
        self.userNameInfo.setText(_fromUtf8(""))
        self.userNameInfo.setObjectName(_fromUtf8("userNameInfo"))
        self.balanceLab = QtGui.QLabel(self.centralWidget)
        self.balanceLab.setGeometry(QtCore.QRect(20, 50, 46, 13))
        self.balanceLab.setObjectName(_fromUtf8("balanceLab"))
        self.frozenLab = QtGui.QLabel(self.centralWidget)
        self.frozenLab.setGeometry(QtCore.QRect(20, 80, 46, 13))
        self.frozenLab.setObjectName(_fromUtf8("frozenLab"))
        self.balanceInfo = QtGui.QLabel(self.centralWidget)
        self.balanceInfo.setGeometry(QtCore.QRect(80, 50, 491, 16))
        self.balanceInfo.setStyleSheet(_fromUtf8("color: rgb(143, 218, 22);"))
        self.balanceInfo.setText(_fromUtf8(""))
        self.balanceInfo.setObjectName(_fromUtf8("balanceInfo"))
        self.frozenInfo = QtGui.QLabel(self.centralWidget)
        self.frozenInfo.setGeometry(QtCore.QRect(80, 80, 491, 16))
        self.frozenInfo.setStyleSheet(_fromUtf8("color: rgb(170, 170, 255);"))
        self.frozenInfo.setText(_fromUtf8(""))
        self.frozenInfo.setObjectName(_fromUtf8("frozenInfo"))
        self.mainTab = QtGui.QTabWidget(self.centralWidget)
        self.mainTab.setGeometry(QtCore.QRect(10, 100, 531, 511))
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.marketTab = QtGui.QWidget()
        self.marketTab.setObjectName(_fromUtf8("marketTab"))
        self.asksLab = QtGui.QLabel(self.marketTab)
        self.asksLab.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.asksLab.setObjectName(_fromUtf8("asksLab"))
        self.asksDepth = QtGui.QTableWidget(self.marketTab)
        self.asksDepth.setGeometry(QtCore.QRect(0, 40, 521, 211))
        self.asksDepth.setLineWidth(1)
        self.asksDepth.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.asksDepth.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.asksDepth.setRowCount(1)
        self.asksDepth.setColumnCount(2)
        self.asksDepth.setObjectName(_fromUtf8("asksDepth"))
        item = QtGui.QTableWidgetItem()
        self.asksDepth.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.asksDepth.setHorizontalHeaderItem(1, item)
        self.bidsLab = QtGui.QLabel(self.marketTab)
        self.bidsLab.setGeometry(QtCore.QRect(10, 260, 31, 16))
        self.bidsLab.setObjectName(_fromUtf8("bidsLab"))
        self.bidsDepth = QtGui.QTableWidget(self.marketTab)
        self.bidsDepth.setGeometry(QtCore.QRect(0, 280, 521, 211))
        self.bidsDepth.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.bidsDepth.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.bidsDepth.setRowCount(1)
        self.bidsDepth.setColumnCount(2)
        self.bidsDepth.setObjectName(_fromUtf8("bidsDepth"))
        item = QtGui.QTableWidgetItem()
        self.bidsDepth.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bidsDepth.setHorizontalHeaderItem(1, item)
        self.freshButton = QtGui.QPushButton(self.marketTab)
        self.freshButton.setGeometry(QtCore.QRect(450, 10, 61, 21))
        self.freshButton.setObjectName(_fromUtf8("freshButton"))
        self.manualRadio = QtGui.QRadioButton(self.marketTab)
        self.manualRadio.setGeometry(QtCore.QRect(390, 10, 61, 21))
        self.manualRadio.setChecked(True)
        self.manualRadio.setObjectName(_fromUtf8("manualRadio"))
        self.autoRadio = QtGui.QRadioButton(self.marketTab)
        self.autoRadio.setGeometry(QtCore.QRect(270, 10, 51, 21))
        self.autoRadio.setObjectName(_fromUtf8("autoRadio"))
        self.periodSpin = QtGui.QSpinBox(self.marketTab)
        self.periodSpin.setEnabled(False)
        self.periodSpin.setGeometry(QtCore.QRect(320, 10, 42, 21))
        self.periodSpin.setMinimum(3)
        self.periodSpin.setObjectName(_fromUtf8("periodSpin"))
        self.periodLab = QtGui.QLabel(self.marketTab)
        self.periodLab.setGeometry(QtCore.QRect(370, 10, 20, 21))
        self.periodLab.setObjectName(_fromUtf8("periodLab"))
        self.currencyPaireCombo = QtGui.QComboBox(self.marketTab)
        self.currencyPaireCombo.setGeometry(QtCore.QRect(100, 10, 69, 21))
        self.currencyPaireCombo.setObjectName(_fromUtf8("currencyPaireCombo"))
        self.currencyPaireCombo.addItem(_fromUtf8(""))
        self.deep_spinner = QtGui.QSpinBox(self.marketTab)
        self.deep_spinner.setGeometry(QtCore.QRect(220, 10, 42, 22))
        self.deep_spinner.setMinimum(1)
        self.deep_spinner.setProperty("value", 10)
        self.deep_spinner.setObjectName(_fromUtf8("deep_spinner"))
        self.label = QtGui.QLabel(self.marketTab)
        self.label.setGeometry(QtCore.QRect(180, 10, 31, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.mainTab.addTab(self.marketTab, _fromUtf8(""))
        self.orderTab = QtGui.QWidget()
        self.orderTab.setObjectName(_fromUtf8("orderTab"))
        self.freshButtono = QtGui.QPushButton(self.orderTab)
        self.freshButtono.setGeometry(QtCore.QRect(450, 10, 61, 21))
        self.freshButtono.setObjectName(_fromUtf8("freshButtono"))
        self.buyList = QtGui.QTableWidget(self.orderTab)
        self.buyList.setEnabled(True)
        self.buyList.setGeometry(QtCore.QRect(0, 40, 521, 211))
        self.buyList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.buyList.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.buyList.setRowCount(1)
        self.buyList.setColumnCount(5)
        self.buyList.setObjectName(_fromUtf8("buyList"))
        item = QtGui.QTableWidgetItem()
        self.buyList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.buyList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.buyList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.buyList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.buyList.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.buyList.setItem(0, 3, item)
        self.periodSpino = QtGui.QSpinBox(self.orderTab)
        self.periodSpino.setEnabled(False)
        self.periodSpino.setGeometry(QtCore.QRect(320, 10, 42, 21))
        self.periodSpino.setMinimum(3)
        self.periodSpino.setProperty("value", 3)
        self.periodSpino.setObjectName(_fromUtf8("periodSpino"))
        self.sellLab = QtGui.QLabel(self.orderTab)
        self.sellLab.setGeometry(QtCore.QRect(10, 260, 31, 16))
        self.sellLab.setObjectName(_fromUtf8("sellLab"))
        self.sellList = QtGui.QTableWidget(self.orderTab)
        self.sellList.setGeometry(QtCore.QRect(0, 280, 521, 211))
        self.sellList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.sellList.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.sellList.setRowCount(1)
        self.sellList.setColumnCount(5)
        self.sellList.setObjectName(_fromUtf8("sellList"))
        item = QtGui.QTableWidgetItem()
        self.sellList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sellList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sellList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sellList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sellList.setHorizontalHeaderItem(4, item)
        self.autoRadioo = QtGui.QRadioButton(self.orderTab)
        self.autoRadioo.setGeometry(QtCore.QRect(270, 10, 61, 21))
        self.autoRadioo.setObjectName(_fromUtf8("autoRadioo"))
        self.manualRadioo = QtGui.QRadioButton(self.orderTab)
        self.manualRadioo.setGeometry(QtCore.QRect(390, 10, 61, 21))
        self.manualRadioo.setChecked(True)
        self.manualRadioo.setObjectName(_fromUtf8("manualRadioo"))
        self.periodLab2 = QtGui.QLabel(self.orderTab)
        self.periodLab2.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.periodLab2.setObjectName(_fromUtf8("periodLab2"))
        self.buyLab = QtGui.QLabel(self.orderTab)
        self.buyLab.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.buyLab.setObjectName(_fromUtf8("buyLab"))
        self.currencyPaireComboo = QtGui.QComboBox(self.orderTab)
        self.currencyPaireComboo.setGeometry(QtCore.QRect(170, 10, 69, 21))
        self.currencyPaireComboo.setObjectName(_fromUtf8("currencyPaireComboo"))
        self.currencyPaireComboo.addItem(_fromUtf8(""))
        self.mainTab.addTab(self.orderTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Palm Coin", None))
        self.platformLab.setText(_translate("MainWindow", "Platform:", None))
        self.userNameLab.setText(_translate("MainWindow", "User name:", None))
        self.balanceLab.setText(_translate("MainWindow", "Balance:", None))
        self.frozenLab.setText(_translate("MainWindow", "Frozen:", None))
        self.asksLab.setText(_translate("MainWindow", "Asks", None))
        item = self.asksDepth.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price", None))
        item = self.asksDepth.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Volume", None))
        self.bidsLab.setText(_translate("MainWindow", "Bids", None))
        item = self.bidsDepth.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price", None))
        item = self.bidsDepth.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Volume", None))
        self.freshButton.setText(_translate("MainWindow", "Fresh", None))
        self.manualRadio.setText(_translate("MainWindow", "Manual", None))
        self.autoRadio.setText(_translate("MainWindow", "Auto", None))
        self.periodLab.setText(_translate("MainWindow", "s", None))
        self.currencyPaireCombo.setItemText(0, _translate("MainWindow", "BTC/CNY", None))
        self.label.setText(_translate("MainWindow", "Deep:", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.marketTab), _translate("MainWindow", "Market", None))
        self.freshButtono.setText(_translate("MainWindow", "Fresh", None))
        item = self.buyList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price", None))
        item = self.buyList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount", None))
        item = self.buyList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total Price", None))
        item = self.buyList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.buyList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date-Time", None))
        __sortingEnabled = self.buyList.isSortingEnabled()
        self.buyList.setSortingEnabled(False)
        item = self.buyList.item(0, 3)
        item.setText(_translate("MainWindow", "gfsgfs", None))
        self.buyList.setSortingEnabled(__sortingEnabled)
        self.sellLab.setText(_translate("MainWindow", "Sell", None))
        item = self.sellList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price", None))
        item = self.sellList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount", None))
        item = self.sellList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total Price", None))
        item = self.sellList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.sellList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date-Time", None))
        self.autoRadioo.setText(_translate("MainWindow", "Auto", None))
        self.manualRadioo.setText(_translate("MainWindow", "Manual", None))
        self.periodLab2.setText(_translate("MainWindow", "s", None))
        self.buyLab.setText(_translate("MainWindow", "Buy", None))
        self.currencyPaireComboo.setItemText(0, _translate("MainWindow", "BTC/CNY", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.orderTab), _translate("MainWindow", "Orders", None))

